### ISSUE TITLE
hi getting same error again

### ISSUE THREAD

**Issue by magboo** [kdcz/3s_atc#21] opened 2017-02-24 00:40 UTC
![capture](https://cloud.githubusercontent.com/assets/25304953/23285546/2afb69f6-fa32-11e6-97be-375b30b20beb.JPG)

**Comment by manbearcoon** [comment] 2017-02-24 01:52
Tested today. I'm also seeing the same issue where the tool says, "No sizes available" and the Status is, "Error! Check logs".

This was with Product ID S81826 in Adidas Canada. Prior I had done a stock lookup in Tools and it confirmed that stock was available.

I closed the app, re-launched, added even more sizes, tried again and it carted.

Keep up the good work, hope this bug can get fixed.

**Comment by pfcpinto** [comment] 2017-02-24 06:44
Testing 25 accounts with 25 proxies using the test URL that program crashes as the accounts start to get past splash page. Any idea why? running on a 16core server with 64gb of ram.

**Comment by kdcz** [comment] 2017-02-24 13:52
I am working on a fix atm for the sizes issue
@pfcpinto i'll see what I can do

**Comment by kdcz** [comment] 2017-02-24 18:21
Pushed a new udapte, check it out please

**Comment by CashHash123** [comment] 2017-02-24 18:34
Any way to import profiles from old version?

**Comment by kdcz** [comment] 2017-02-24 18:37
Nope, it should be the last time that an update remove your profiles because I added a field to the profile class and your profiles are "encrypted" in a single script then decrypted so it would fuck up everything

**Comment by CashHash123** [comment] 2017-02-24 18:42
Got ya, All good,   
Adding em back now.

Thanks for everything bro

**Comment by pfcpinto** [comment] 2017-02-24 18:57
deleted all the old files redownloaded the zip folder and my accounts and proxies are still in the program.

**Comment by kdcz** [comment] 2017-02-24 18:58
Yeah the update that deleted your profiles was the previous one

**Comment by pfcpinto** [comment] 2017-02-24 19:01
is there currently no way to remove proxies once you added them?

**Comment by kdcz** [comment] 2017-02-24 19:04
Select them and press delete key on your keyboard same for your profiles

**Comment by txsneakerhead23** [comment] 2017-02-24 20:02
i just tested on adidas.ca and still get the error of sizes not available

**Comment by kdcz** [comment] 2017-02-24 20:17
Pushed an update, please update your WHOLE folder and give me some feedbacks please

**Comment by txsneakerhead23** [comment] 2017-02-24 20:43
okay just tested again and it shows No sizes available when you only input one size but if i add 2 sizes it adds to cart. Lets says there is size 9,10,11 available. If i just input size 9 it shows No sizes available
but if input size 9 and 8.5 even though 8.5 is out of stock it adds the 9.

**Comment by kdcz** [comment] 2017-02-24 20:49
If you close the program and opens it again with the profile loaded, does it works ?

**Comment by txsneakerhead23** [comment] 2017-02-24 20:59
status is getting stuck on checking sizes

**Comment by kdcz** [comment] 2017-02-24 22:06
It's an hypothesis but I guess actually the yeezy release in Australia and China slows down the adidas servers

**Comment by kdcz** [comment] 2017-02-24 22:14
Pushed a new update for the size not available issue but when status is stuck on Checking Sizes... it's actually not the program's fault but more like adidas blocking the requests because of the yeezy releases

**Comment by jalex1** [comment] 2017-02-24 23:19
Is there anything that we can do or is this likely to be an issue on the release? Also for the zebras, when it retrives the hmac and sitekey, what should happen then on the bot as in testing have never been able to get that far?
btw sent you some pms on reddit

**Comment by pfcpinto** [comment] 2017-02-27 20:50
Anyone have success this weekend?

**Comment by jalex1** [comment] 2017-02-27 21:13
nope

**Comment by kdcz** [comment] 2017-03-01 19:34
Nope, adidas blocked all proxies, I will implement a multi session from one IP feature soon

**Comment by kdcz** [comment] 2017-03-03 15:01
check new update, size checking should be fixed for good

**Closed** 2017-03-05 13:55 UTC
