### ISSUE TITLE
New Browser

### ISSUE THREAD

**Issue by jalex1** [kdcz/3s_atc#33] opened 2017-06-17 09:53 UTC
Hey, thanks for the update, just ran a test on the old splash page for the zebra release, noticed this message on the splash page 'Sorry! Your browser isn't supported.
Please update to a modern browser.' Could this be an issue if not using a conventional browser?

**Comment by rb1997** [comment] 2017-06-17 13:09
shouldn't be. this is standard with the test page.

**Comment by kdcz** [comment] 2017-06-17 13:23
I guess it's because the user agent that I didn't change, I'll push a new update today with various bug fix

**Comment by rb1997** [comment] 2017-06-17 17:33
When i try to login using the 'login' before running i get an error preventing the browser's .exe from opening.

**Comment by jalex1** [comment] 2017-06-17 18:53
I also get an error when not using splash, using either run or login, the program crashes when trying to login using the new broswer

**Comment by kdcz** [comment] 2017-06-17 19:41
Update:  -New feature : guest mode(available for splash mode only)
-You can show/hide window just like before
-Custom user agent

@rb1997 which error ? Btw the login process doesn't use the custom browser but a browser inside the program

@jalex1 Yes it occured to me aswell, I'll work on that tomorrow !

**Comment by rb1997** [comment] 2017-06-17 20:38
@kdcz same error both you and @jalex1 are encountering, application crashes when logging in in non splash mode.

**Comment by felixthechef** [comment] 2017-06-18 01:33
I am too getting an error trying to log in. It just crashes straight away.

**Comment by kdcz** [comment] 2017-06-18 13:25
Download the new version, should be fixed now !

**Comment by rb1997** [comment] 2017-06-18 23:00
@kdcz works great now! One last suggestion, when the application is closed, all the browsers remain open and the only way to close all at once is to end the 3s_atc process tree. any way to make sure when the main application is closed, all created processes close with it?

**Comment by kdcz** [comment] 2017-06-19 14:19
Update :  -You can now login to Gmail to prevent from captcha freezing bug
-All 3s_atc - browser.exe are closed properly

@rb1997 thanks for the report, fixed ;)

**Comment by jalex1** [comment] 2017-06-20 19:47
Hi just tried out the update, seems to be working great. However cannot figure out how to end the browsers without going on task manager and closing them down there. Also it would be useful if the sizes chosen are saved (do not need to re do them for each new profile). But great stuff. Keep up the good work!

**Comment by jalex1** [comment] 2017-06-20 19:51
Also for the zebra release does anyone know how to avoid getting multiple orders cancelled (such as changing the shipping address or the payment?)

**Comment by rb1997** [comment] 2017-06-20 22:10
yeah @kdcz, i second the idea of a "duplicate profile" button where we can copy all the same info over to each profile whilst just needing to edit the email/password fields. Doing the sizes for each new profile and the url etc even though we want them all the same is really time consuming.

**Comment by kdcz** [comment] 2017-06-20 22:39
@jalex1 Regarding the cpu thing, I don't think it's an issue but more like something I forgot to add.Let me explain, the browser and the program are communicating by creating a 'pipe', each pipe has a name depending on the session number ONLY(ex session_0 is the name of the pipe for the first session), so if you run a second program the first session of it will connect to the already existing 'session_0' pipe and both programs are receiving the same informations,so yeah I'll fix that by adding an idientifier for each program.

@jalex1 If usually the delivery man doesnt care about who signs his paper I guess you can put whatever first name you want
Also I heard that each order has to be on different IP,so once its in your card, login on a different device(with a proxy/vpn if you don't have a dynamic IP or use connection sharing with your phone) and cop!
Last thing you can do is create multiple Paypal accounts, transfer money to it without linking your bank card so Adidas won't detect that you used the same PayPal account.

@rb1997 @jalex1 I'll make that happen !

**Comment by kdcz** [comment] 2017-06-21 16:06
Update : 
-You can now duplicate a profile, just right click on the profile and press 'Duplicate'
-Added current process id to each pipe name
-Added an url bar in 3s_atc browser in case you want to switch to d3stryr-3stripes

**Comment by jalex1** [comment] 2017-06-21 21:08
Thanks for the update, seems to be working well

**Comment by rb1997** [comment] 2017-06-21 22:19
works great. will test extensively tomorrow and give my final verdict. For now, its close to perfect. Great work man!!

**Comment by rb1997** [comment] 2017-06-21 23:32
Just tested a bit more. After attempting to log in 12 profiles/accounts i was banned from adidas eu login server, confirmed by visiting the site in chrome browser and getting access denied where login fields should be. Not sure how to avoid this or how long this ban will last. I hope its lifted before saturday.

https://snag.gy/n4HRci.jpg

**Comment by kdcz** [comment] 2017-06-22 10:44
@rb1997 I guess they have a DDos protection that blocks you when you send too much requests

**Comment by mskh1327** [comment] 2017-06-23 07:31
This should be an awesome bot, Thank you! After duplicating and adding profiles, some profiles' sizes show up blank after closing and reopening the bot. One account's sizes disappear in front of my eyes.

**Comment by rb1997** [comment] 2017-06-23 08:04
temporary fix for this is to close and reopen programme after each duplication

**Comment by kdcz** [comment] 2017-06-23 12:06
Thanks for the report guys, it should be fixed now.

**Comment by jalex1** [comment] 2017-06-24 07:56
Splash live in the eu now, getting error on 8/10 sessions failing to set up i think

**Comment by jalex1** [comment] 2017-06-24 07:58
However whn inopen the browsers some of them are on the spalsh page, seems they dont know if they are or not

**Comment by kdcz** [comment] 2017-06-24 08:32
Just restart it working fine here

**Comment by jalex1** [comment] 2017-06-24 09:19
Okay so I got through on one of the sessions however the captacha would not solve and also the checkout button would not appear. However managed to cop 4 manually

**Comment by kdcz** [comment] 2017-06-24 09:33
Congrats ! I past splash on 1 session but for sole some reason the browser closed bruh 
Took an L on this one

**Comment by jalex1** [comment] 2017-06-25 14:46
I noticed that if once you cop one, if you then open a new tab on chrome or on the same tab go to the adidas home page , and use the search bar to go to the yeezy page, then refresh you skip splash and so can order multiple pairs.

**Comment by jalex1** [comment] 2017-06-28 08:37
Just used the program on the ultra boost splash page. Failed to set up some of the sessions again but i manually typed in the url on them. Got through to the product page however had a captcha issue on every session. Could not finish the captcha- would not end just kept asking me new ones- even when i logged into gmail.

**Comment by kdcz** [comment] 2017-06-29 13:13
Thanks for the tip didnt know about this one !
Yeah I noticed there are some issue when running multiple sessions and with the captcha thing, I'm going to work on that and also rewrite the whole UI to make it smaller and simpler

**Comment by jalex1** [comment] 2017-06-29 13:29
Great sounds good!

**Comment by kdcz** [comment] 2017-06-30 17:06
Update :  -Smaller and simpler UI
-No captcha/duplicate/clientid checkbox, just enter the necessary infos in the textboxes
-Unique splashmode/splash url for all profiles
-Removed useless infos from the datagrids
-Right click on a session when the status is "EXTRACTED SESSION" to show all infos(hmac, sitekey, clientid, duplicate)
-Fixed bugs with client inventory checking and sessions

Next update I'll improve captcha solving and add proxy support again because they are currently disabled.

**Comment by kdcz** [comment] 2017-07-10 14:48
-YEEZYSUPPLY support : select YEEZYSUPPLY in splash mode, select your size and click add, then run the guest mode, once the status is on "Done!" show the browser and order your pair.

-3s_atc browser : you can now open the browser without 3s_atc opened, added a back/forward/refresh button, url bar improved

**Comment by felixthechef** [comment] 2017-07-11 02:05
so dope dude! thanks so much!

**Comment by jalex1** [comment] 2017-09-10 18:14
You all ready for the October drop?

**Comment by kdcz** [comment] 2017-09-11 16:15
What drops on october ?

**Comment by jalex1** [comment] 2017-09-11 16:40
Might be some 700s released on yeezy supply apparently

**Comment by kdcz** [comment] 2017-09-11 22:08
Oh okay,I'll push an update for the 700s but I personally find them ugly, I don't understand the hype(if there is one) about these shoes.

**Comment by jalex1** [comment] 2017-09-11 22:25
Yeh fairs mate, i wasn't particularity planning on copping any myself (feel the same as you) but was just wondering if people were

**Comment by jalex1** [comment] 2017-10-22 19:08
Looks like the next yeezy drop will be on the 18th novemeber

**Comment by kdcz** [comment] 2017-10-29 11:32
Yes sir, seems like it's the most limited v2.
3s_atc should work for that release.

**Comment by jalex1** [comment] 2017-11-02 11:51
Hi just tested the latest update, nice work. However once the item is added to cart and it opens the 3s_atc browser, i am unable to click on checkout. Its like some parts of the page do not respond when clicked on?

**Comment by kdcz** [comment] 2017-11-02 17:36
Works well for me, just pushed a new update : you can now choose your browser when carting the product if you have issues ;)

**Comment by jalex1** [comment] 2017-11-03 11:39
Thanks, yes works fine with chrome. great work man

**Closed** 2017-11-13 12:27 UTC
